# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QGPTAgent
                                 A QGIS plugin
 QGPT Agent is LLM Assistant that uses openai GPT model to automate QGIS processes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-04-27
        copyright            : (C) 2023 by Mohammed Nasser
        email                : mohammed.nasser@uofk.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QGPTAgent class from file QGPTAgent.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qgpt_agent import QGPTAgent
    return QGPTAgent(iface)
